### PR TITLE
Add GitHub full support, refactor Highlight and WordCarousel, and fix SpellChecking to work in all tabs

### LINKED ISSUE #4: GitHub textarea size too small and comment field has no spell checking applied
Multiple bugs when using MultiDict for GitHub at the moment:

1. comment boxes, despite being textareas, don't have any spellchecking (checked in console and hwt container is never injected)

2. the highlights break CTR+Z shortcut inside text fields (and probably others?)

3. comment box resizes inside main body text area when writing a new issue:

github-bug-multi

### LINKED ISSUE #15: Refactor the spaghetti code that is the highlight.js file
The highlight.js file should be refactored in such a way that the a highlighter is a class which is instantiated by passing in all necessary properties (i.e. CSS and other style values). The necessary CSS and other style values should be generated with helper functions that do not form part of the core highlighter class.

- [ ] highlighter uses ES6 class syntax (init function removed)
- [ ] helper functions rewritten and moved into helpers file
- [ ] keyup event handler should be split into smaller chunks
- [ ] directory structure updated to make the sense

### LINKED ISSUE #20: Spell checking only applies in a single tab
Switching tabs after a textarea has been spell checked on a different tab prevents the textarea on the newly switched to tab from being spell checked.

See GIF.

bug-switch-tabs

### PR DESCRIPTION
**Pull request by GrayedFox**
- [x] textarea height remembered when applying spell checking/generating 
- [x] spell checking now applied inside comment textareas and new issue textareas in GitHub
- [x] adding or deleting a word using keyboard shortcuts now triggers an immediate re-check
- [x] spell checking no longer breaks when switching tabs
- [x] spell checking works when switching to an already open tab
- [x] spell checking works when switching to a new tab
- [x] spell checking works when reloading the same page

Fixes #4
Fixes #15 
Fixes #20

### CODE REVIEW

**Comment by GrayedFox** [comment]
Note to self:
- prepost node output is always correct and consistently updates before message is sent
- the first time user opens a new tab, the new tab will have spell checking applied
- the original tab, when focusing a text area, will output the prepost message (correct context/scope), however everything output in the message handler will be in the new tab's console (wrong/unexpected scope)

File: src/background.js [hunk 1]
```diff
@@ -99,6 +90,22 @@ function contextListener (info) {
...
+  const tabName = `tab-${tab.id}`
+
+  if (contentPort) {
+    contentPort.onMessage.removeListener(api)
+    contentPort.disconnect()
+    contentPort = null
+  }
+
+  contentPort = browser.tabs.connect(tab.id, { name: tabName })
+  contentPort.onMessage.addListener(api)
```
Comment (GrayedFox) [inline src/background.js]: need to update currentPort to newly created contentPort if we still want content script to be able to call getCustomWords (which it currently does not) - the best time to do this would actually be once the disconnect event fires for the browser popup
